Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -12,6 +12,14 @@ on:
           - us-east-1
           - us-west-1
           - us-west-2
+      terraform_action:
+        description: "Choose the Terraform action (apply, destroy)"
+        required: true
+        default: "apply"
+        type: choice
+        options:
+          - apply
+          - destroy
       create_vpc:
         description: "Set to true to create a VPC"
         required: true
@@ -39,6 +47,38 @@ on:
       create_autoscaling:
         description: "Set to true to create an Autoscaling Group"
         required: true
+        default: false
+        type: choice
+        options:
+          - true
+          - false
+      destroy_vpc:
+        description: "Set to true to destroy the VPC"
+        required: false
+        default: false
+        type: choice
+        options:
+          - true
+          - false
+      destroy_ec2:
+        description: "Set to true to destroy EC2 instance"
+        required: false
+        default: false
+        type: choice
+        options:
+          - true
+          - false
+      destroy_s3:
+        description: "Set to true to destroy an S3 bucket"
+        required: false
+        default: false
+        type: choice
+        options:
+          - true
+          - false
+      destroy_autoscaling:
+        description: "Set to true to destroy Autoscaling Group"
+        required: false
         default: false
         type: choice
         options:
@@ -89,19 +129,37 @@ jobs:
         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
       run: |
-        terraform plan \
-          -var="aws_region=${{ github.event.inputs.aws_region }}" \
-          -var="create_vpc=${{ github.event.inputs.create_vpc }}" \
-          -var="create_ec2=${{ github.event.inputs.create_ec2 }}" \
-          -var="create_s3=${{ github.event.inputs.create_s3 }}" \
-          -var="create_autoscaling=${{ github.event.inputs.create_autoscaling }}" \
-          -var="ami_id=${{ github.event.inputs.ami_id }}" \
-          -var="instance_type=${{ github.event.inputs.instance_type }}" \
-          -var="subnet_id=${{ github.event.inputs.subnet_id }}" \
-          -var="security_group_id=${{ github.event.inputs.security_group_id }}" \
-          -var="s3_bucket_name=${{ github.event.inputs.s3_bucket_name }}"
+        if [ "${{ github.event.inputs.terraform_action }}" == "apply" ]; then
+          terraform plan \
+            -var="aws_region=${{ github.event.inputs.aws_region }}" \
+            -var="create_vpc=${{ github.event.inputs.create_vpc }}" \
+            -var="create_ec2=${{ github.event.inputs.create_ec2 }}" \
+            -var="create_s3=${{ github.event.inputs.create_s3 }}" \
+            -var="create_autoscaling=${{ github.event.inputs.create_autoscaling }}" \
+            -var="ami_id=${{ github.event.inputs.ami_id }}" \
+            -var="instance_type=${{ github.event.inputs.instance_type }}" \
+            -var="subnet_id=${{ github.event.inputs.subnet_id }}" \
+            -var="security_group_id=${{ github.event.inputs.security_group_id }}" \
+            -var="s3_bucket_name=${{ github.event.inputs.s3_bucket_name }}"
+        elif [ "${{ github.event.inputs.terraform_action }}" == "destroy" ]; then
+          terraform plan -destroy \
+            -var="aws_region=${{ github.event.inputs.aws_region }}" \
+            -var="destroy_vpc=${{ github.event.inputs.destroy_vpc }}" \
+            -var="destroy_ec2=${{ github.event.inputs.destroy_ec2 }}" \
+            -var="destroy_s3=${{ github.event.inputs.destroy_s3 }}" \
+            -var="destroy_autoscaling=${{ github.event.inputs.destroy_autoscaling }}" \
+            -var="ami_id=${{ github.event.inputs.ami_id }}" \
+            -var="instance_type=${{ github.event.inputs.instance_type }}" \
+            -var="subnet_id=${{ github.event.inputs.subnet_id }}" \
+            -var="security_group_id=${{ github.event.inputs.security_group_id }}" \
+            -var="s3_bucket_name=${{ github.event.inputs.s3_bucket_name }}"
+        else
+          echo "Invalid terraform_action: ${{ github.event.inputs.terraform_action }}. Exiting."
+          exit 1
+        fi
 
     - name: Terraform Apply
+      if: ${{ github.event.inputs.terraform_action == 'apply' }}
       env:
         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
@@ -117,3 +175,26 @@ jobs:
           -var="subnet_id=${{ github.event.inputs.subnet_id }}" \
           -var="security_group_id=${{ github.event.inputs.security_group_id }}" \
           -var="s3_bucket_name=${{ github.event.inputs.s3_bucket_name }}"
+
+    - name: Terraform Destroy
+      if: ${{ github.event.inputs.terraform_action == 'destroy' }}
+      env:
+        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
+        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+      run: |
+        if [ "${{ github.event.inputs.destroy_vpc }}" == "true" ]; then
+          terraform destroy -auto-approve -target=aws_vpc.example_vpc \
+            -var="aws_region=${{ github.event.inputs.aws_region }}"
+        fi
+        if [ "${{ github.event.inputs.destroy_ec2 }}" == "true" ]; then
+          terraform destroy -auto-approve -target=aws_instance.example_ec2 \
+            -var="aws_region=${{ github.event.inputs.aws_region }}"
+        fi
+        if [ "${{ github.event.inputs.destroy_s3 }}" == "true" ]; then
+          terraform destroy -auto-approve -target=aws_s3_bucket.example_s3 \
+            -var="aws_region=${{ github.event.inputs.aws_region }}"
+        fi
+        if [ "${{ github.event.inputs.destroy_autoscaling }}" == "true" ]; then
+          terraform destroy -auto-approve -target=aws_autoscaling_group.example_autoscaling \
+            -var="aws_region=${{ github.event.inputs.aws_region }}"
+        fi
